### ISSUE TITLE
Bad calibration

### ISSUE THREAD

**Issue by gaowenliang** [uzh-rpg/IROS2019-FPV-VIO-Competition#2]
Thanks for this exciting dataset.
I have tried to use your dataset, however, I find that the calibration quality is not good enough.
Especially, the calibration data of "indoor 45deg" camera, only cover the center of the view.
I know it is hard to collect the calibration data again.
Is it possible to provide more dataset with good calibration data?

**Comment by tcies** [comment]
Hi Wenliang,

it is unfortunately not possible to record another calibration dataset. However,

1. We recently realized that the calibrations provided on the website were mistakenly regressed to the radtan, instead of equidistant, distortion model. With equidistant distortion, the calibration is much better, see #3 .
2. If calibrating yourself, you might have run into https://github.com/ethz-asl/kalibr/issues/99 . That's what happened to us.
